# Generated by Django 4.2.2 on 2023-07-19 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('DeckID', models.IntegerField(primary_key=True, serialize=False)),
                ('DeckName', models.CharField(max_length=254)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.accounts')),
            ],
        ),
    ]
