# Generated by Django 4.2.2 on 2023-07-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_decks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='UserID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
