# Generated by Django 4.2.2 on 2023-07-20 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_delete_decks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('DeckID', models.IntegerField(primary_key=True, serialize=False)),
                ('DeckName', models.CharField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
