# Generated by Django 4.2.2 on 2023-07-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Decks',
        ),
    ]
