# Generated by Django 4.2.2 on 2023-08-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='DeckID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
